name: Deploy static documentation to Pages

on:
  push:
    branches: ["development", "7-add-ci-and-mdbook-documentation"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install mdbook dependencies
        run: |
        pushd manual
        bash install.sh
        popd

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate documentation
        run: |
          bash doc.sh
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
