name: Deploy static documentation to Pages

on:
  push:
    branches: ["development", "development_openrpcdoc_fix"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bash install.sh

      - name: Install mdbook dependencies
        run: bash manual/install.sh

      - name: Generate documentation
        run: |
          bash doc.sh
